#!/bin/bash
cd ${BASH_SOURCE%/*}/../../..

binaryDir=Build/Release
inputDir=$1/Inputs
outputDir=$1/Experiments/FastTA/JEA

mkdir --parents $outputDir/TA/FlowPatterns

cmake -D CMAKE_BUILD_TYPE=Release -S . -B $binaryDir
cmake --build $binaryDir

export LC_ALL=C
export OMP_NUM_THREADS=1
export OMP_DYNAMIC=false
export OMP_PROC_BIND=true
export OMP_PLACES=cores

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=0 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/Dij_rand_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/Dij_rand_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/Dij_rand_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/Dij_rand_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a Dijkstra -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/Dij_rand_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=0 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/Bi-Dij_rand_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/Bi-Dij_rand_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/Bi-Dij_rand_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/Bi-Dij_rand_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/Bi-Dij_rand_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=0 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_rand_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_rand_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_rand_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_rand_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_rand_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=0 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_sorted_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_sorted_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_sorted_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_sorted_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_sorted_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=2 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k4_NoSIMD_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k4_NoSIMD_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k4_NoSIMD_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k4_NoSIMD_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k4_NoSIMD_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=2 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k4_SSE_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k4_SSE_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k4_SSE_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k4_SSE_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k4_SSE_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=3 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k8_NoSIMD_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k8_NoSIMD_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k8_NoSIMD_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k8_NoSIMD_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k8_NoSIMD_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=3 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k8_SSE_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k8_SSE_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k8_SSE_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k8_SSE_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k8_SSE_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=3 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k8_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k8_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k8_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k8_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k8_AVX_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=4 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k16_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k16_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k16_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k16_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k16_AVX_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=5 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k32_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k32_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k32_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k32_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k32_AVX_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=6 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k64_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k64_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k64_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k64_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k64_AVX_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=0 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_rand_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_rand_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_rand_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_rand_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_rand_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=0 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_sorted_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_sorted_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_sorted_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_sorted_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_sorted_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=2 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k4_NoSIMD_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k4_NoSIMD_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k4_NoSIMD_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k4_NoSIMD_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k4_NoSIMD_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=2 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k4_SSE_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k4_SSE_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k4_SSE_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k4_SSE_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k4_SSE_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=3 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k8_NoSIMD_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k8_NoSIMD_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k8_NoSIMD_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k8_NoSIMD_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k8_NoSIMD_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=3 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=ON -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k8_SSE_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k8_SSE_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k8_SSE_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k8_SSE_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k8_SSE_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=3 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k8_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k8_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k8_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k8_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k8_AVX_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=4 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k16_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k16_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k16_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k16_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k16_AVX_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=5 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k32_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k32_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k32_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k32_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k32_AVX_L-peak

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=6 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k64_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k64_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k64_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k64_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k64_AVX_L-peak

for numCores in 2 4 8 12 16; do
  export OMP_NUM_THREADS=$numCores
  cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=0 -D TA_USE_SIMD_SEARCH=OFF -D DISABLE_AVX=ON -S . -B $binaryDir
  cmake --build $binaryDir --target AssignTraffic
  $binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_rand_S-morn_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_rand_S-even_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_rand_S-day_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_rand_S-week_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_rand_L-peak_${numCores}cores

  cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=5 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
  cmake --build $binaryDir --target AssignTraffic
  $binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k32_AVX_S-morn_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k32_AVX_S-even_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k32_AVX_S-day_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k32_AVX_S-week_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k32_AVX_L-peak_${numCores}cores
done

cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K=5 -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1 -n 28 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -flow $outputDir/TA/FlowPatterns/S-morn
cmake -D CMAKE_BUILD_TYPE=Release -D TA_LOG_K= -D TA_USE_SIMD_SEARCH=ON -D DISABLE_AVX=OFF -S . -B $binaryDir
cmake --build $binaryDir --target AssignTraffic
