#!/bin/bash
cd ${BASH_SOURCE%/*}/../../..
scons variant=Release

binaryDir=Build/Release
inputDir=$1/Inputs
outputDir=$1/Experiments/FastTA/JEA

mkdir --parents $outputDir/P2P

export OMP_DYNAMIC=false
export OMP_PROC_BIND=true
export OMP_PLACES=cores

for numCores in 1 2 4 8 12 16; do
  export OMP_NUM_THREADS=$numCores
  $binaryDir/Launchers/RunP2PAlgo -a CCH-custom -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -s $inputDir/SepDecomps/Visum_Stuttgart_nd30.sep.bin -o $outputDir/P2P/Customization_Stuttgart_${numCores}cores
  $binaryDir/Launchers/RunP2PAlgo -a CCH-custom -g $inputDir/Graphs/DIMACS_eur.gr.bin      -s $inputDir/SepDecomps/DIMACS_eur_nd30.sep.bin      -o $outputDir/P2P/Customization_Europe_${numCores}cores
done

$binaryDir/Launchers/RunP2PAlgo -a CH -h $inputDir/CHs/DIMACS_eur_time.ch.bin -d $inputDir/ODPairs/P2P/DIMACS_eur_rank_time.csv -o $outputDir/P2P/LocalQueries_time_CH
$binaryDir/Launchers/RunP2PAlgo -a CH -h $inputDir/CHs/DIMACS_eur_dist.ch.bin -d $inputDir/ODPairs/P2P/DIMACS_eur_rank_dist.csv -o $outputDir/P2P/LocalQueries_dist_CH

$binaryDir/Launchers/RunP2PAlgo -a CCH-Dij -no-stall -g $inputDir/Graphs/DIMACS_eur.gr.bin -s $inputDir/SepDecomps/DIMACS_eur_nd30.sep.bin -d $inputDir/ODPairs/P2P/DIMACS_eur_rank_time.csv -o $outputDir/P2P/LocalQueries_time_CCHDij
$binaryDir/Launchers/RunP2PAlgo -a CCH-Dij -no-stall -g $inputDir/Graphs/DIMACS_eur.gr.bin -s $inputDir/SepDecomps/DIMACS_eur_nd30.sep.bin -d $inputDir/ODPairs/P2P/DIMACS_eur_rank_dist.csv -o $outputDir/P2P/LocalQueries_dist_CCHDij -l

scons variant=Release def=NO_FAST_ELIMINATION_TREE_QUERY RunP2PAlgo
$binaryDir/Launchers/RunP2PAlgo -a CCH-tree -g $inputDir/Graphs/DIMACS_eur.gr.bin -s $inputDir/SepDecomps/DIMACS_eur_nd30.sep.bin -d $inputDir/ODPairs/P2P/DIMACS_eur_rank_time.csv -o $outputDir/P2P/LocalQueries_time_CCHTree
$binaryDir/Launchers/RunP2PAlgo -a CCH-tree -g $inputDir/Graphs/DIMACS_eur.gr.bin -s $inputDir/SepDecomps/DIMACS_eur_nd30.sep.bin -d $inputDir/ODPairs/P2P/DIMACS_eur_rank_dist.csv -o $outputDir/P2P/LocalQueries_dist_CCHTree -l
scons variant=Release RunP2PAlgo

$binaryDir/Launchers/RunP2PAlgo -a CCH-tree -g $inputDir/Graphs/DIMACS_eur.gr.bin -s $inputDir/SepDecomps/DIMACS_eur_nd30.sep.bin -d $inputDir/ODPairs/P2P/DIMACS_eur_rank_time.csv -o $outputDir/P2P/LocalQueries_time_CCHTreeFast
$binaryDir/Launchers/RunP2PAlgo -a CCH-tree -g $inputDir/Graphs/DIMACS_eur.gr.bin -s $inputDir/SepDecomps/DIMACS_eur_nd30.sep.bin -d $inputDir/ODPairs/P2P/DIMACS_eur_rank_dist.csv -o $outputDir/P2P/LocalQueries_dist_CCHTreeFast -l
