#!/bin/bash
cd ${BASH_SOURCE%/*}/../../..
scons variant=Release

binaryDir=Build/Release
inputDir=$1/Inputs
outputDir=$1/Experiments/FastTA/JEA

mkdir --parents $outputDir/TA/FlowPatterns

export OMP_NUM_THREADS=1
export OMP_DYNAMIC=false
export OMP_PROC_BIND=true
export OMP_PLACES=cores

scons variant=Release def=TA_LOG_K=0 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/Dij_rand_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/Dij_rand_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/Dij_rand_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/Dij_rand_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a Dijkstra -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/Dij_rand_L-peak

scons variant=Release def=TA_LOG_K=0 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/Bi-Dij_rand_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/Bi-Dij_rand_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/Bi-Dij_rand_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/Bi-Dij_rand_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a Bi-Dijkstra -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/Bi-Dij_rand_L-peak

scons variant=Release def=TA_LOG_K=0 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_rand_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_rand_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_rand_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_rand_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_rand_L-peak

scons variant=Release def=TA_LOG_K=0 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_sorted_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_sorted_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_sorted_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_sorted_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_sorted_L-peak

scons variant=Release def=TA_LOG_K=2 def=TA_NO_SIMD_SEARCH AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k4_NoSIMD_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k4_NoSIMD_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k4_NoSIMD_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k4_NoSIMD_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k4_NoSIMD_L-peak

scons variant=Release def=TA_LOG_K=2 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k4_SSE_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k4_SSE_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k4_SSE_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k4_SSE_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k4_SSE_L-peak

scons variant=Release def=TA_LOG_K=3 def=TA_NO_SIMD_SEARCH AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k8_NoSIMD_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k8_NoSIMD_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k8_NoSIMD_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k8_NoSIMD_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k8_NoSIMD_L-peak

scons variant=Release def=TA_LOG_K=3 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k8_SSE_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k8_SSE_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k8_SSE_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k8_SSE_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k8_SSE_L-peak

scons variant=Release simd=avx def=TA_LOG_K=3 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k8_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k8_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k8_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k8_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k8_AVX_L-peak

scons variant=Release simd=avx def=TA_LOG_K=4 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k16_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k16_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k16_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k16_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k16_AVX_L-peak

scons variant=Release simd=avx AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k32_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k32_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k32_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k32_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k32_AVX_L-peak

scons variant=Release simd=avx def=TA_LOG_K=6 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_k64_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_k64_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_k64_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_k64_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_k64_AVX_L-peak

scons variant=Release def=TA_LOG_K=0 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_rand_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_rand_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_rand_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_rand_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_rand_L-peak

scons variant=Release def=TA_LOG_K=0 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_sorted_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_sorted_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_sorted_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_sorted_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_sorted_L-peak

scons variant=Release def=TA_LOG_K=2 def=TA_NO_SIMD_SEARCH AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k4_NoSIMD_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k4_NoSIMD_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k4_NoSIMD_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k4_NoSIMD_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k4_NoSIMD_L-peak

scons variant=Release def=TA_LOG_K=2 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k4_SSE_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k4_SSE_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k4_SSE_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k4_SSE_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k4_SSE_L-peak

scons variant=Release def=TA_LOG_K=3 def=TA_NO_SIMD_SEARCH AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k8_NoSIMD_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k8_NoSIMD_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k8_NoSIMD_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k8_NoSIMD_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k8_NoSIMD_L-peak

scons variant=Release def=TA_LOG_K=3 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k8_SSE_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k8_SSE_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k8_SSE_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k8_SSE_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k8_SSE_L-peak

scons variant=Release simd=avx def=TA_LOG_K=3 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k8_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k8_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k8_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k8_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k8_AVX_L-peak

scons variant=Release simd=avx def=TA_LOG_K=4 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k16_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k16_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k16_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k16_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k16_AVX_L-peak

scons variant=Release simd=avx AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k32_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k32_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k32_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k32_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k32_AVX_L-peak

scons variant=Release simd=avx def=TA_LOG_K=6 AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k64_AVX_S-morn
$binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k64_AVX_S-even
$binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k64_AVX_S-day
$binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k64_AVX_S-week
$binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k64_AVX_L-peak

for numCores in 2 4 8 12 16; do
  export OMP_NUM_THREADS=$numCores
  scons variant=Release def=TA_LOG_K=0 AssignTraffic
  $binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CH_rand_S-morn_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CH_rand_S-even_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CH_rand_S-day_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CH -o random -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CH_rand_S-week_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CH -o random -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CH_rand_L-peak_${numCores}cores

  scons variant=Release simd=avx AssignTraffic
  $binaryDir/Launchers/AssignTraffic -p 1  -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -stat $outputDir/TA/CCH_k32_AVX_S-morn_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 1  -n 34 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_even.csv -stat $outputDir/TA/CCH_k32_AVX_S-even_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 10 -n 39 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_day.csv  -stat $outputDir/TA/CCH_k32_AVX_S-day_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 70 -n 29 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_week.csv -stat $outputDir/TA/CCH_k32_AVX_S-week_${numCores}cores
  $binaryDir/Launchers/AssignTraffic -p 1  -n 20 -a CCH -o sorted -g $inputDir/Graphs/Visum_London.gr.bin    -d $inputDir/ODPairs/TA/Visum_London_peak.csv    -stat $outputDir/TA/CCH_k32_AVX_L-peak_${numCores}cores
done

scons variant=Release simd=avx AssignTraffic
$binaryDir/Launchers/AssignTraffic -p 1 -n 28 -a CCH -o sorted -g $inputDir/Graphs/Visum_Stuttgart.gr.bin -d $inputDir/ODPairs/TA/Visum_Stuttgart_morn.csv -flow $outputDir/TA/FlowPatterns/S-morn
scons variant=Release AssignTraffic
