p1 = Program(
    source=['AssignTraffic.cpp'], parse_flags='-DCSV_IO_NO_THREAD -fopenmp', LIBS=['routingkit'])
p2 = Program(
    source=['RunP2PAlgo.cpp'], parse_flags='-DCSV_IO_NO_THREAD -fopenmp', LIBS=['routingkit'])

Alias('AssignTraffic', p1)
Alias('RunP2PAlgo', p2)

Return('p1', 'p2')
