p1 = Program(
    source=['AssignTraffic.cpp'], parse_flags='-DCSV_IO_NO_THREAD -fopenmp', LIBS=['routingkit'])
p2 = Program(
    source=['CalculateDemand.cpp'], parse_flags='-DCSV_IO_NO_THREAD -fopenmp', LIBS=['proj'])
p3 = Program(
    source=['RunP2PAlgo.cpp'], parse_flags='-DCSV_IO_NO_THREAD -fopenmp', LIBS=['routingkit'])

Alias('AssignTraffic', p1)
Alias('CalculateDemand', p2)
Alias('RunP2PAlgo', p3)

Return('p1', 'p2', 'p3')
