p01 = Program(source=['CalibrateOsm.cpp'], LIBS=['routingkit'])
p02 = Program(source=['ComputeDijkstraRanks.cpp'], parse_flags='-DCSV_IO_NO_THREAD')
p03 = Program(source=['ComputeDistances.cpp'], parse_flags='-DCSV_IO_NO_THREAD')
p04 = Program(
    source=['ComputeUnionBoundary.cpp'], parse_flags='-DCSV_IO_NO_THREAD',
    LIBS=['CGAL', 'gmp', 'mpfr', 'proj'])
p05 = Program(
    source=['ConvertGraph.cpp'], parse_flags='-DCSV_IO_NO_THREAD', LIBS=['proj', 'routingkit'])
p06 = Program(source=['GenerateMatchingODPairs.cpp'], LIBS=['routingkit'])
p07 = Program(source=['GenerateODPairs.cpp'], parse_flags='-DCSV_IO_NO_THREAD')
p08 = Program(source=['ParseMobiTopp.cpp'], parse_flags='-DCSV_IO_NO_THREAD')
p09 = Program(source=['ParseMtxFile.cpp'], parse_flags='-DCSV_IO_NO_THREAD')
p10 = Program(source=['RadiationModel.cpp'], parse_flags='-DCSV_IO_NO_THREAD', LIBS=['proj'])

Alias('CalibrateOsm', p01)
Alias('ComputeDijkstraRanks', p02)
Alias('ComputeDistances', p03)
Alias('ComputeUnionBoundary', p04)
Alias('ConvertGraph', p05)
Alias('GenerateMatchingODPairs', p06)
Alias('GenerateODPairs', p07)
Alias('ParseMobiTopp', p08)
Alias('ParseMtxFile', p09)
Alias('RadiationModel', p10)

Return('p01', 'p02', 'p03', 'p04', 'p05', 'p06', 'p07', 'p08', 'p09', 'p10')
